/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    TzButton: typeof import('./src/components/TzButton/TzButton.vue')['default']
    TzHeading: typeof import('./src/components/TzHeading/TzHeading.vue')['default']
    TzIcon: typeof import('./src/components/TzIcon/TzIcon.vue')['default']
    TzInput: typeof import('./src/components/TzInput/TzInput.vue')['default']
    TzStyles: typeof import('./src/components/TzStyles/TzStyles.vue')['default']
    TzTextarea: typeof import('./src/components/TzTextarea/TzTextarea.vue')['default']
    TzToggleTheme: typeof import('./src/components/TzToggleTheme/TzToggleTheme.vue')['default']
  }
}
