/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    TzButton: typeof import('./src/components/TzButton.vue')['default']
    TzHeading: typeof import('./src/components/TzHeading.vue')['default']
    TzIcon: typeof import('./src/components/TzIcon.vue')['default']
    TzStyles: typeof import('./src/components/TzStyles.vue')['default']
  }
}
